services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      TZ: Europe/Kyiv
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняет базу

volumes:
  postgres_data:
